/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ihm;

import accesAuxDonnees.FTPUploadfile;
import java.sql.Date;
import java.text.SimpleDateFormat;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import metier.Photo;
import metier.emplacementPhoto;

/**
 *
 * @author samy
 */
public class FenetrePhoto extends javax.swing.JDialog {

    public static String[] toutesLesExtensions={"JPG","JPEG","TIF","BMP","RAW"};
    private boolean etatSortie;
    private Photo laPhoto;
    private emplacementPhoto chemin;
    
    public FenetrePhoto(java.awt.Frame parent,Photo unePhoto,emplacementPhoto chemin) {
        super(parent, true); 
        this.laPhoto=unePhoto;
        this.chemin=chemin;
        etatSortie = false;
        initComponents();       
    }
    
    public boolean doModal() {
        setVisible(true);
        return etatSortie;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        titrePhoto = new javax.swing.JTextField();
        chargerPhotoBt = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lieuPhotoBt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        datePhotoBt = new com.toedter.calendar.JDateChooser();
        valider = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Inserer une photo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));

        jLabel3.setFont(new java.awt.Font("Garamond", 0, 16)); // NOI18N
        jLabel3.setText("Choisir la photo ");

        titrePhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titrePhotoActionPerformed(evt);
            }
        });

        chargerPhotoBt.setText("parcourir..");
        chargerPhotoBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chargerPhotoBtActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Garamond", 0, 16)); // NOI18N
        jLabel2.setText("Lieu de la photo ");

        lieuPhotoBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lieuPhotoBtActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Garamond", 0, 16)); // NOI18N
        jLabel4.setText("Date de la photo");

        datePhotoBt.setDateFormatString("d-MM-yyyy");

        valider.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        valider.setText("Inserer");
        valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3))
                    .addComponent(jLabel4))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(valider, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lieuPhotoBt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(titrePhoto, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(datePhotoBt, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                        .addGap(14, 14, 14)
                        .addComponent(chargerPhotoBt)
                        .addGap(18, 18, 18))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(chargerPhotoBt)
                    .addComponent(titrePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lieuPhotoBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(datePhotoBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(valider, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void titrePhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titrePhotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titrePhotoActionPerformed

    private void chargerPhotoBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chargerPhotoBtActionPerformed
        // TODO add your handling code here:
        JFileChooser choix=new JFileChooser();
        choix.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int retour=choix.showOpenDialog(this);
        chemin.setChemin_dest("/public_html/CPOA/php/assets/photosVip/");
        if(retour==JFileChooser.APPROVE_OPTION)
        {
            choix.getSelectedFile();
            chemin.setChemin_src(choix.getSelectedFile().getAbsolutePath());
            String nomAncienFichier=choix.getSelectedFile().getName();
            titrePhoto.setText(nomAncienFichier);
        }
    }//GEN-LAST:event_chargerPhotoBtActionPerformed

    private void lieuPhotoBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lieuPhotoBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lieuPhotoBtActionPerformed

    private void validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat formateur = new SimpleDateFormat("yyyy-MM-dd");
        boolean virus=true;
        try {
            //On verifie qu'on a bien selectionner une photo
            if(titrePhoto.getText().isEmpty())
            {
                throw new Exception("Vous n'avez pas selectionnez de photo");
            }
            
            //Comparaison avec les extensions possibles d'une image pour verifier que le document selectionné est bien une image
            String leTitre=titrePhoto.getText();
            String[] decompositionPhoto=leTitre.split("\\.");
            String extension=decompositionPhoto[decompositionPhoto.length-1].toUpperCase();
            for(String ext: toutesLesExtensions)
            {
                if(extension.compareTo(ext)==0)
                {
                    virus=false;
                }
            }
            if(virus==true)
            {
                throw new Exception("Le document selectionné n'est pas une photo !");
            }
            
            //On verifie que le champ lieu n'est pas vide
            if (lieuPhotoBt.getText().isEmpty()) {
                throw new Exception("champ lieu photo vide");
            }     
            laPhoto.setLieu(lieuPhotoBt.getText());

            //On verifie que le champ date n'est pas vide
            if (datePhotoBt.getDate()==null) {
                throw new Exception("champ date mariage vide");
            }
            laPhoto.setDatePhoto(Date.valueOf(formateur.format(datePhotoBt.getDate())));

            //Aucune exception appelé, on sort par la voie normal (en passant à l'état à true)
            etatSortie = true;
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erreur", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_validerActionPerformed

    public void passageFalse()
    {
        etatSortie=false;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chargerPhotoBt;
    private com.toedter.calendar.JDateChooser datePhotoBt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField lieuPhotoBt;
    private javax.swing.JTextField titrePhoto;
    private javax.swing.JButton valider;
    // End of variables declaration//GEN-END:variables
}
