/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ihm;

import java.util.logging.Level;
import java.util.logging.Logger;
import metier.Film;
import metier.LigneActeurFilm;
import metier.LigneRealisateurFilm;
import modelVip.ModeleJComboBoxGenre;
import modelVip.ModeleJTableActeur;
import modelVip.ModeleJTableFilm;
import modelVip.ModeleJTableRealisateur;

/**
 *
 * @author samy
 */
public class FenetreAffichageFilms extends javax.swing.JDialog {

    private ModeleJTableFilm lesFilms;
    private ModeleJComboBoxGenre lesGenres;
    private ModeleJTableActeur lesActeurs;
    private ModeleJTableRealisateur lesRealisateurs;
    private boolean etatSortie;
    private java.awt.Frame parent;
    
    public FenetreAffichageFilms(java.awt.Frame parent, ModeleJTableFilm lesFilms,ModeleJComboBoxGenre lesGenres,ModeleJTableActeur lesActeurs,ModeleJTableRealisateur lesRealisateurs) {
        super(parent, true);
        this.lesFilms=lesFilms;
        this.lesGenres=lesGenres;
        this.lesActeurs=lesActeurs;
        this.lesRealisateurs=lesRealisateurs;
        this.parent=parent;
        this.etatSortie=false;
        initComponents();
        try {
            lesFilms.chargerLesFilms();
        } catch (Exception ex) {
            Logger.getLogger(FenetreApplication.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public boolean doModal() {
        setVisible(true);
        return etatSortie;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        laTableR = new javax.swing.JTable();
        AjoutFilmBt = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        AjoutActeurBt = new javax.swing.JButton();
        AjoutRealisateurBt = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel1.setText("Les films");

        laTableR.setModel(lesFilms);
        jScrollPane1.setViewportView(laTableR);

        AjoutFilmBt.setText("Ajouter un film");
        AjoutFilmBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjoutFilmBtActionPerformed(evt);
            }
        });

        AjoutActeurBt.setText("Ajouter un acteur *");
        AjoutActeurBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjoutActeurBtActionPerformed(evt);
            }
        });

        AjoutRealisateurBt.setText("Ajouter un réalisateur *");
        AjoutRealisateurBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjoutRealisateurBtActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Pour un film déjà crée, ");

        jLabel3.setText("* Vous devez selectionnez un Film pour enclenchez le processus");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(201, 201, 201))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(AjoutFilmBt)
                        .addGap(180, 180, 180))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel2)
                        .addGap(0, 305, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jSeparator1)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(AjoutActeurBt)
                        .addGap(53, 53, 53)
                        .addComponent(AjoutRealisateurBt)
                        .addGap(67, 67, 67))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(AjoutFilmBt)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AjoutActeurBt)
                    .addComponent(AjoutRealisateurBt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AjoutRealisateurBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjoutRealisateurBtActionPerformed
        // TODO add your handling code here:
        int ligne = laTableR.getSelectedRow();
        int numVisa=(int)lesFilms.getValueAt(ligne,0);
        LigneRealisateurFilm unRealisateur = new LigneRealisateurFilm();
        unRealisateur.setNumVisa(numVisa);
        lesRealisateurs.viderListe();
        FenetreRealisateur fenRealisateur = new FenetreRealisateur(parent,lesRealisateurs,unRealisateur);
        try
        {
        if (fenRealisateur.doModal() == true) {
                lesFilms.ajouterRealisateur(unRealisateur);
            }
        } catch (Exception e) {
            System.out.println("Exception pour l'ajout d'un acteur dans un film : " + e.getMessage());
        }
    }//GEN-LAST:event_AjoutRealisateurBtActionPerformed

    private void AjoutFilmBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjoutFilmBtActionPerformed
        // TODO add your handling code here:
        try {
            Film leFilm = new Film();
            FenetreAjouterFilm fenFilm = new FenetreAjouterFilm(parent,lesGenres,leFilm);
            if (fenFilm.doModal() == true) {
                lesFilms.insererInfoFilm(leFilm);
            }
        } catch (Exception e) {
            System.out.println("Exception à l'ajout du film : " + e.getMessage());
        }
    }//GEN-LAST:event_AjoutFilmBtActionPerformed

    private void AjoutActeurBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjoutActeurBtActionPerformed
        // TODO add your handling code here:
        int ligne = laTableR.getSelectedRow();
        int numVisa=(int)lesFilms.getValueAt(ligne,0);
        LigneActeurFilm acteur = new LigneActeurFilm();
        acteur.setNumVisa(numVisa);
        lesActeurs.viderListe();
        FenetreActeur fenActeur = new FenetreActeur(parent,lesActeurs,acteur);
        try
        {
        if (fenActeur.doModal() == true) {
                lesFilms.ajouterActeur(acteur);
            }
        } catch (Exception e) {
            System.out.println("Exception pour l'ajout d'un acteur dans un film : " + e.getMessage());
        }
    }//GEN-LAST:event_AjoutActeurBtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AjoutActeurBt;
    private javax.swing.JButton AjoutFilmBt;
    private javax.swing.JButton AjoutRealisateurBt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable laTableR;
    // End of variables declaration//GEN-END:variables
}
