/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ihm;

import java.sql.Date;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import metier.Evenement;
import metier.LigneMariage;
import metier.Vip;
import modelVip.ModeleJTableEvenement;

/**
 *
 * @author samy
 */
public class FenetreDivorce extends javax.swing.JDialog {

    /**
     * Creates new form FenetreDivorc
     */
    private LigneMariage leDivorce;
    private ModeleJTableEvenement leModele;
    private boolean etatSortie;
    
    public FenetreDivorce(java.awt.Frame parent, ModeleJTableEvenement modele, LigneMariage divorce) {
        super(parent, true);
        this.leDivorce=divorce;
        this.leModele=modele;
        etatSortie = false;
        initComponents();
        
         try {
            leModele.chargerLesMariages();
        } catch (Exception ex) {
            Logger.getLogger(FenetreApplication.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public boolean doModal() {
        setVisible(true);
        return etatSortie;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        laTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        validerBt = new javax.swing.JButton();
        dateDivorceBt = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Imprint MT Shadow", 0, 24)); // NOI18N
        jLabel1.setText("Divorce");

        laTable.setModel(leModele);
        jScrollPane1.setViewportView(laTable);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Date du divorce  :");

        validerBt.setText("Valider");
        validerBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerBtActionPerformed(evt);
            }
        });

        dateDivorceBt.setDateFormatString("d-MM-yyyy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(validerBt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(281, 281, 281)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(195, 195, 195)
                                .addComponent(jLabel2)
                                .addGap(27, 27, 27)
                                .addComponent(dateDivorceBt, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateDivorceBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(validerBt)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void validerBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerBtActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat formateur = new SimpleDateFormat("yyyy-MM-dd");
        Date dateDivorce, dateMariage;
        try {
            int ligne = laTable.getSelectedRow();
            
            if (dateDivorceBt.getDate()==null) {
                throw new Exception("champ date vide");
            }
            dateDivorce=Date.valueOf(formateur.format(dateDivorceBt.getDate()));
            dateMariage=(Date) leModele.getValueAt(ligne,7);
            if(dateDivorce.before(dateMariage) || dateDivorce.equals(dateMariage))
            {
                throw new Exception("ERREUR : la date de divorce est avant (ou égale) la date de mariage");
            }
            leDivorce.setDateDivorce(dateDivorce);
            
            //ajouter le vip 1 à l'evenement pour le divorce
            int numVip1 = (int) leModele.getValueAt(ligne,0);
            leDivorce.setNumVip1(numVip1);
            String nomVip1 = (String) leModele.getValueAt(ligne,1);
            leDivorce.setNomVip1(nomVip1);
            String prenomVip1 = (String) leModele.getValueAt(ligne,2);
            leDivorce.setPrenomVip1(prenomVip1);
            
            //ajouter le vip 2 à l'evenement pour le divorce
            int numVip2 = (int) leModele.getValueAt(ligne,3);          
            leDivorce.setNumVip2(numVip2);
            String nomVip2 = (String) leModele.getValueAt(ligne,4);
            leDivorce.setNomVip2(nomVip2);
            String prenomVip2 = (String) leModele.getValueAt(ligne,5);
            leDivorce.setPrenomVip2(prenomVip2);
            
            //ajouter le lieu du mariage
            String lieuMariage = (String) leModele.getValueAt(ligne,6);
            leDivorce.setLieu(lieuMariage);
            
            //ajouter la date de mariage
            leDivorce.setDateMariage(dateMariage);
            
            etatSortie = true;
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erreur", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_validerBtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dateDivorceBt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable laTable;
    private javax.swing.JButton validerBt;
    // End of variables declaration//GEN-END:variables
}
