/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ihm;

import java.sql.Date;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import metier.Vip;

/**
 *
 * @author Alain
 */
public class FenetreSaisieVip extends javax.swing.JDialog {

    private static int leNumVip;
    private Vip emp;
    private boolean etatSortie;

    public FenetreSaisieVip(java.awt.Frame parent, Vip emp,int numVip) {
        super(parent, true);  // mode modal       
        this.emp = emp;
        etatSortie = false;
        leNumVip=numVip;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prenomBt = new javax.swing.JTextField();
        NomBt = new javax.swing.JTextField();
        lbNom = new javax.swing.JLabel();
        lbJob = new javax.swing.JLabel();
        btValid = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        civiliteVip = new javax.swing.JLabel();
        dateNaiss = new javax.swing.JLabel();
        lieuNaiss = new javax.swing.JLabel();
        CodeRole = new javax.swing.JLabel();
        pays = new javax.swing.JLabel();
        statut = new javax.swing.JLabel();
        CiviliteBt = new javax.swing.JComboBox();
        lieuNaissBt = new javax.swing.JTextField();
        paysBt = new javax.swing.JTextField();
        roleBt = new javax.swing.JComboBox();
        codeStatutBt = new javax.swing.JComboBox();
        dateNaissanceBt = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Saisie d'un employé");

        lbNom.setText("Nom ");

        lbJob.setText("Prenom");

        btValid.setText("Valider");
        btValid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btValidActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        jLabel1.setText("Inserer un VIP");

        civiliteVip.setText("Civilite");

        dateNaiss.setText("Date de naissance");

        lieuNaiss.setText("Lieu de naissance");

        CodeRole.setText("Code role");

        pays.setText("pays");

        statut.setText("Statut");

        CiviliteBt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mr", "Mme" }));
        CiviliteBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CiviliteBtActionPerformed(evt);
            }
        });

        lieuNaissBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lieuNaissBtActionPerformed(evt);
            }
        });

        paysBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paysBtActionPerformed(evt);
            }
        });

        roleBt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "R", "NA" }));

        codeStatutBt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "C", "M", "D" }));
        codeStatutBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeStatutBtActionPerformed(evt);
            }
        });

        dateNaissanceBt.setDateFormatString("d-MM-yyyy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(statut)
                                    .addComponent(pays)
                                    .addComponent(CodeRole))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addComponent(codeStatutBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(roleBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(CiviliteBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(prenomBt, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(NomBt, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(paysBt, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(lieuNaissBt, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(dateNaissanceBt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)))))))
                            .addComponent(dateNaiss)
                            .addComponent(civiliteVip)
                            .addComponent(lbJob, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNom, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lieuNaiss)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(btValid))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel1)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNom))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbJob)
                    .addComponent(prenomBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(civiliteVip, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CiviliteBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateNaiss, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateNaissanceBt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lieuNaiss)
                    .addComponent(lieuNaissBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CodeRole)
                    .addComponent(roleBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pays)
                    .addComponent(paysBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codeStatutBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statut))
                .addGap(18, 18, 18)
                .addComponent(btValid)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btValidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btValidActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat formateur = new SimpleDateFormat("yyyy-MM-dd");
        try {
            leNumVip++;
            emp.setNumVip(leNumVip);   
            
            if (NomBt.getText().isEmpty()) {
                throw new Exception("champ nom vide");
            }
            emp.setNomVip(NomBt.getText());
            
            if (prenomBt.getText().isEmpty()) {
                throw new Exception("champ prenom vide");
            }
            emp.setPrenomVip(prenomBt.getText());
            
             if (dateNaissanceBt.getDate()==null) {
                throw new Exception("champ date mariage vide");
            }
            emp.setDateNaissance(Date.valueOf(formateur.format(dateNaissanceBt.getDate())));
            
            emp.setCivilite(String.valueOf(CiviliteBt.getSelectedItem()));
            
            if (lieuNaissBt.getText().isEmpty()) {
                throw new Exception("champ lieu de naissance vide");
            }
            emp.setLieuNaissance(lieuNaissBt.getText());
            
            emp.setCodeRole(String.valueOf(roleBt.getSelectedItem()));
            
            if (paysBt.getText().isEmpty()) {
                throw new Exception("champ pays vide");
            }
            emp.setPays(paysBt.getText());
            
            emp.setCodeStatut(String.valueOf(codeStatutBt.getSelectedItem()));
            
            etatSortie = true;
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erreur", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btValidActionPerformed

    private void CiviliteBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CiviliteBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CiviliteBtActionPerformed

    private void lieuNaissBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lieuNaissBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lieuNaissBtActionPerformed

    private void paysBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paysBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paysBtActionPerformed

    private void codeStatutBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeStatutBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codeStatutBtActionPerformed

    public boolean doModal() {
        setVisible(true);
        return etatSortie;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CiviliteBt;
    private javax.swing.JLabel CodeRole;
    private javax.swing.JTextField NomBt;
    private javax.swing.JButton btValid;
    private javax.swing.JLabel civiliteVip;
    private javax.swing.JComboBox codeStatutBt;
    private javax.swing.JLabel dateNaiss;
    private com.toedter.calendar.JDateChooser dateNaissanceBt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbJob;
    private javax.swing.JLabel lbNom;
    private javax.swing.JLabel lieuNaiss;
    private javax.swing.JTextField lieuNaissBt;
    private javax.swing.JLabel pays;
    private javax.swing.JTextField paysBt;
    private javax.swing.JTextField prenomBt;
    private javax.swing.JComboBox roleBt;
    private javax.swing.JLabel statut;
    // End of variables declaration//GEN-END:variables
}
