/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ihm;

import javax.swing.JOptionPane;
import metier.Vip;

/**
 *
 * @author Alain
 */
public class FenetreSaisie extends javax.swing.JDialog {

    public static int leNumVip=16;
    private Vip emp;
    private boolean etatSortie;

    public FenetreSaisie(java.awt.Frame parent, Vip emp) {
        super(parent, true);  // mode modal       
        this.emp = emp;
        etatSortie = false;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txPrenom = new javax.swing.JTextField();
        txNom = new javax.swing.JTextField();
        lbNom = new javax.swing.JLabel();
        lbJob = new javax.swing.JLabel();
        btValid = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        civiliteVip = new javax.swing.JLabel();
        dateNaiss = new javax.swing.JLabel();
        lieuNaiss = new javax.swing.JLabel();
        CodeRole = new javax.swing.JLabel();
        pays = new javax.swing.JLabel();
        statut = new javax.swing.JLabel();
        CiviliteBt = new javax.swing.JComboBox();
        jourBt = new javax.swing.JTextField();
        moisBt = new javax.swing.JTextField();
        anneeBt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lieuNaissBt = new javax.swing.JTextField();
        paysBt = new javax.swing.JTextField();
        roleBt = new javax.swing.JComboBox();
        codeStatutBt = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Saisie d'un employé");

        lbNom.setText("Nom ");

        lbJob.setText("Prenom");

        btValid.setText("Valider");
        btValid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btValidActionPerformed(evt);
            }
        });

        jLabel1.setText("Inserer un VIP");

        civiliteVip.setText("Civilite");

        dateNaiss.setText("Date de naissance (JJ/MM/AAAA)");

        lieuNaiss.setText("Lieu de naissance");

        CodeRole.setText("Code role");

        pays.setText("pays");

        statut.setText("Statut");

        CiviliteBt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mr", "Mme" }));
        CiviliteBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CiviliteBtActionPerformed(evt);
            }
        });

        jourBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jourBtActionPerformed(evt);
            }
        });

        jLabel2.setText("/");

        jLabel3.setText("/");

        lieuNaissBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lieuNaissBtActionPerformed(evt);
            }
        });

        paysBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paysBtActionPerformed(evt);
            }
        });

        roleBt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "R", "NA" }));

        codeStatutBt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "C", "M", "D" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statut)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dateNaiss)
                                .addGap(18, 18, 18)
                                .addComponent(jourBt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(moisBt))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbNom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbJob, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(civiliteVip))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CiviliteBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(txNom, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(btValid)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(anneeBt, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(lieuNaiss)
                                    .addGap(18, 18, 18))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(CodeRole)
                                    .addGap(56, 56, 56)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pays)
                                .addGap(79, 79, 79)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(paysBt, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roleBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lieuNaissBt, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codeStatutBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNom)
                    .addComponent(txNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbJob)
                    .addComponent(txPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(civiliteVip)
                    .addComponent(CiviliteBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateNaiss)
                    .addComponent(jourBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moisBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anneeBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lieuNaiss)
                    .addComponent(lieuNaissBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CodeRole)
                    .addComponent(roleBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pays)
                    .addComponent(paysBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statut)
                    .addComponent(codeStatutBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btValid)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btValidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btValidActionPerformed
        // TODO add your handling code here:
        try {
            emp.setNumVip(leNumVip++);         
            if (txNom.getText().isEmpty()) {
                throw new Exception("champ nom vide");
            }
            emp.setNomVip(txNom.getText());
            if (txPrenom.getText().isEmpty()) {
                throw new Exception("champ prenom vide");
            }
            emp.setPrenomVip(txPrenom.getText());
            if (jourBt.getText().isEmpty() || moisBt.getText().isEmpty()|| anneeBt.getText().isEmpty()) {
                throw new Exception("champ date incomplet ou vide");
            }
            emp.setCivilite(String.valueOf(CiviliteBt.getSelectedItem()));
            emp.setDateNaissance(jourBt.getText()+ '/' + moisBt.getText() + '/' + anneeBt.getText());
            if (lieuNaissBt.getText().isEmpty()) {
                throw new Exception("champ lieu de naissance vide");
            }
            emp.setLieuNaissance(lieuNaissBt.getText());
            emp.setCodeRole(String.valueOf(roleBt.getSelectedItem()));
            if (paysBt.getText().isEmpty()) {
                throw new Exception("champ pays vide");
            }
            emp.setPays(paysBt.getText());
            emp.setCodeStatut(String.valueOf(codeStatutBt.getSelectedItem()));
            etatSortie = true;
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erreur", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btValidActionPerformed

    private void CiviliteBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CiviliteBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CiviliteBtActionPerformed

    private void jourBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jourBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jourBtActionPerformed

    private void lieuNaissBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lieuNaissBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lieuNaissBtActionPerformed

    private void paysBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paysBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paysBtActionPerformed

    public boolean doModal() {
        setVisible(true);
        return etatSortie;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CiviliteBt;
    private javax.swing.JLabel CodeRole;
    private javax.swing.JTextField anneeBt;
    private javax.swing.JButton btValid;
    private javax.swing.JLabel civiliteVip;
    private javax.swing.JComboBox codeStatutBt;
    private javax.swing.JLabel dateNaiss;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jourBt;
    private javax.swing.JLabel lbJob;
    private javax.swing.JLabel lbNom;
    private javax.swing.JLabel lieuNaiss;
    private javax.swing.JTextField lieuNaissBt;
    private javax.swing.JTextField moisBt;
    private javax.swing.JLabel pays;
    private javax.swing.JTextField paysBt;
    private javax.swing.JComboBox roleBt;
    private javax.swing.JLabel statut;
    private javax.swing.JTextField txNom;
    private javax.swing.JTextField txPrenom;
    // End of variables declaration//GEN-END:variables
}
