/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ihm;

import static com.sun.org.apache.xalan.internal.xsltc.compiler.util.Type.Int;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import metier.Film;
import modelVip.ModeleJComboBoxGenre;

/**
 *
 * @author p1422662
 */
public class FenetreAjouterFilm extends javax.swing.JDialog {

    /**
     * Creates new form FenetreFilm
     */
    private ModeleJComboBoxGenre leModele;
    private boolean etatSortie;
    private Film leFilm;
    
    public FenetreAjouterFilm(java.awt.Frame parent,ModeleJComboBoxGenre leModele,Film leFilm) {
        super(parent, true); 
        this.leModele=leModele;
        this.leFilm=leFilm;
        this.etatSortie=false;
        initComponents();
        //Remplissage du jcombobox
         try {
            leModele.chargerLesGenres();
        } catch (Exception ex) {
            Logger.getLogger(FenetreApplication.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
     public boolean doModal() {
        setVisible(true);
        return etatSortie;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomFilmBt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        anneeFilmBt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ValiderBt = new javax.swing.JButton();
        genreBt = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel1.setText("Ajout Film");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Nom film : ");

        nomFilmBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomFilmBtActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Année film : ");

        anneeFilmBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anneeFilmBtActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Genre film :");

        ValiderBt.setText("Valider");
        ValiderBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValiderBtActionPerformed(evt);
            }
        });

        genreBt.setModel(leModele);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomFilmBt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(anneeFilmBt, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(genreBt, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(ValiderBt)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomFilmBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(anneeFilmBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(genreBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(ValiderBt)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomFilmBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomFilmBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomFilmBtActionPerformed

    private void anneeFilmBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anneeFilmBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anneeFilmBtActionPerformed

    private void ValiderBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValiderBtActionPerformed
        // TODO add your handling code here:
         try {          
            int numVisa=leModele.returnMaxVisa();
            numVisa++;
            leFilm.setNumVisa(numVisa);
            
            if (nomFilmBt.getText().isEmpty()) {
                throw new Exception("champ nom film vide");
            }
            leFilm.setNomFilm(nomFilmBt.getText());
            
            if (anneeFilmBt.getText().isEmpty()) {
                throw new Exception("champ annee film vide");
            }
            else
            {
                int annee=Integer.parseInt(anneeFilmBt.getText());
                if(annee<1900 || annee>2017)
                {
                   throw new Exception("année du film impossible");
                }
                leFilm.setAnnee(annee);
            }
           
            if (genreBt.getSelectedItem()== null) {
                throw new Exception("champ genre vide");
            }
            leFilm.setGenre(String.valueOf(genreBt.getSelectedItem()));
            
            etatSortie = true;
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erreur", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_ValiderBtActionPerformed
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ValiderBt;
    private javax.swing.JTextField anneeFilmBt;
    private javax.swing.JComboBox genreBt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nomFilmBt;
    // End of variables declaration//GEN-END:variables
}
