/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ihm;

import java.util.logging.Level;
import java.util.logging.Logger;
import metier.Film;
import metier.LigneActeurFilm;
import metier.LigneRealisateurFilm;
import modelVip.ModeleJComboBoxGenre;
import modelVip.ModeleJTableActeur;
import modelVip.ModeleJTableFilm;
import modelVip.ModeleJTableRealisateur;

/**
 *
 * @author samy
 */
public class FenetreAffichageFilms extends javax.swing.JDialog {

    private ModeleJTableFilm lesFilms;
    private ModeleJComboBoxGenre lesGenres;
    private ModeleJTableActeur lesActeurs;
    private ModeleJTableRealisateur lesRealisateurs;
    private boolean etatSortie;
    private java.awt.Frame parent;
    
    public FenetreAffichageFilms(java.awt.Frame parent, ModeleJTableFilm lesFilms,ModeleJComboBoxGenre lesGenres,ModeleJTableActeur lesActeurs,ModeleJTableRealisateur lesRealisateurs) {
        super(parent, true);
        this.lesFilms=lesFilms;
        this.lesGenres=lesGenres;
        this.lesActeurs=lesActeurs;
        this.lesRealisateurs=lesRealisateurs;
        this.parent=parent;
        this.etatSortie=false;
        initComponents();
        try {
            lesFilms.chargerLesFilms();
        } catch (Exception ex) {
            Logger.getLogger(FenetreApplication.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public boolean doModal() {
        setVisible(true);
        return etatSortie;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        laTableR = new javax.swing.JTable();
        AjoutFilmBt = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        AjoutActeurBt = new javax.swing.JButton();
        AjoutRealisateurBt = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Les films");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(242, 242, 242))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(19, 19, 19))
        );

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setForeground(new java.awt.Color(0, 153, 153));

        laTableR.setModel(lesFilms);
        jScrollPane1.setViewportView(laTableR);

        AjoutFilmBt.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        AjoutFilmBt.setText("Ajouter un film");
        AjoutFilmBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjoutFilmBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(AjoutFilmBt)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(AjoutFilmBt, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));

        AjoutActeurBt.setFont(new java.awt.Font("Monotype Corsiva", 0, 19)); // NOI18N
        AjoutActeurBt.setText("Ajouter un acteur *");
        AjoutActeurBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjoutActeurBtActionPerformed(evt);
            }
        });

        AjoutRealisateurBt.setFont(new java.awt.Font("Monotype Corsiva", 0, 19)); // NOI18N
        AjoutRealisateurBt.setText("Ajouter un réalisateur *");
        AjoutRealisateurBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjoutRealisateurBtActionPerformed(evt);
            }
        });

        jLabel3.setText("* Vous devez selectionnez un Film pour enclenchez le processus");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(AjoutActeurBt, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AjoutRealisateurBt)
                .addGap(64, 64, 64))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AjoutRealisateurBt, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AjoutActeurBt, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AjoutFilmBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjoutFilmBtActionPerformed
        // TODO add your handling code here:
        try {
            Film leFilm = new Film();
            FenetreAjouterFilm fenFilm = new FenetreAjouterFilm(parent,lesGenres,leFilm);
            if (fenFilm.doModal() == true) {
                lesFilms.insererInfoFilm(leFilm);
            }
            lesGenres.removeList();
        } catch (Exception e) {
            System.out.println("Exception à l'ajout du film : " + e.getMessage());
        }
    }//GEN-LAST:event_AjoutFilmBtActionPerformed

    private void AjoutActeurBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjoutActeurBtActionPerformed
        // TODO add your handling code here:
        int ligne = laTableR.getSelectedRow();
        int numVisa=(int)lesFilms.getValueAt(ligne,0);
        LigneActeurFilm acteur = new LigneActeurFilm();
        acteur.setNumVisa(numVisa);
        lesActeurs.viderListe();
        FenetreActeur fenActeur = new FenetreActeur(parent,lesActeurs,acteur);
        try
        {
            if (fenActeur.doModal() == true) {
                lesFilms.ajouterActeur(acteur);
            }
        } catch (Exception e) {
            System.out.println("Exception pour l'ajout d'un acteur dans un film : " + e.getMessage());
        }
    }//GEN-LAST:event_AjoutActeurBtActionPerformed

    private void AjoutRealisateurBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjoutRealisateurBtActionPerformed
        // TODO add your handling code here:
        int ligne = laTableR.getSelectedRow();
        int numVisa=(int)lesFilms.getValueAt(ligne,0);
        LigneRealisateurFilm unRealisateur = new LigneRealisateurFilm();
        unRealisateur.setNumVisa(numVisa);
        lesRealisateurs.viderListe();
        FenetreRealisateur fenRealisateur = new FenetreRealisateur(parent,lesRealisateurs,unRealisateur);
        try
        {
            if (fenRealisateur.doModal() == true) {
                lesFilms.ajouterRealisateur(unRealisateur);
            }
        } catch (Exception e) {
            System.out.println("Exception pour l'ajout d'un acteur dans un film : " + e.getMessage());
        }
    }//GEN-LAST:event_AjoutRealisateurBtActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AjoutActeurBt;
    private javax.swing.JButton AjoutFilmBt;
    private javax.swing.JButton AjoutRealisateurBt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable laTableR;
    // End of variables declaration//GEN-END:variables
}
